package cmd

import (
	"alexandria/internal/database"
	"alexandria/internal/logger"
	"alexandria/internal/ticket"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var (
	title       string
	description string
	ticketType  string
	criticalpath bool
	priority    string
	assignedTo  string
	tags        string
	createdBy   string
	project     string
)

var createCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new ticket",
	Long:  `Create a new ticket with the specified title, description, type, priority, and other attributes.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		logger.Log.Debug("creating ticket", "title", title, "project", project, "type", ticketType)

		// Validate required fields
		if title == "" {
			logger.Log.Error("validation failed", "error", "title is required")
			return fmt.Errorf("title is required")
		}

		// Parse type
		tType := ticket.Type(ticketType)
		if !tType.Valid() {
			logger.Log.Error("validation failed", "error", "invalid type", "type", ticketType)
			return fmt.Errorf("invalid type: %s (must be: bug, feature, or task)", ticketType)
		}

		// Parse priority
		tPriority := ticket.Priority(priority)
		if !tPriority.Valid() {
			logger.Log.Error("validation failed", "error", "invalid priority", "priority", priority)
			return fmt.Errorf("invalid priority: %s (must be: low, medium, or high)", priority)
		}

		// Parse tags
		var tagList []string
		if tags != "" {
			tagList = strings.Split(tags, ",")
			for i, tag := range tagList {
				tagList[i] = strings.TrimSpace(tag)
			}
			logger.Log.Debug("parsed tags", "count", len(tagList), "tags", tagList)
		}

		// Create ticket (ID will be auto-generated by database)
		newTicket := ticket.Ticket{
			Type:         tType,
			Title:        title,
			Description:  description,
			CriticalPath: criticalpath,
			Status:       ticket.StatusOpen, // Default to open
			Priority:     tPriority,
			Tags:         tagList,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		}

		// Handle optional fields
		if assignedTo != "" {
			newTicket.AssignedTo = &assignedTo
			logger.Log.Debug("assigned ticket", "assignee", assignedTo)
		}
		if createdBy != "" {
			newTicket.CreatedBy = &createdBy
			logger.Log.Debug("set creator", "creator", createdBy)
		}

		// Validate project is provided
		if project == "" {
			logger.Log.Error("validation failed", "error", "project is required")
			return fmt.Errorf("project is required")
		}

		// Save ticket to database
		db := database.GetDB()
		if db == nil {
			logger.Log.Error("database not initialized")
			return fmt.Errorf("database not initialized")
		}

		logger.Log.Debug("saving ticket to database", "project", project)
		if err := newTicket.Create(db, project); err != nil {
			logger.Log.Error("failed to save ticket", "error", err, "project", project)
			return fmt.Errorf("failed to save ticket: %w", err)
		}

		logger.Log.Info("ticket created successfully", "id", newTicket.ID, "title", title, "project", project)

		// Output as JSON
		jsonData, err := json.MarshalIndent(newTicket, "", "  ")
		if err != nil {
			logger.Log.Error("failed to marshal ticket", "error", err)
			return fmt.Errorf("failed to marshal ticket: %w", err)
		}

		fmt.Println("Ticket created and saved successfully:")
		fmt.Println(string(jsonData))

		return nil
	},
}

func init() {
	rootCmd.AddCommand(createCmd)

	createCmd.Flags().StringVarP(&title, "title", "t", "", "Ticket title (required)")
	createCmd.Flags().StringVarP(&description, "description", "d", "", "Ticket description")
	createCmd.Flags().StringVar(&ticketType, "type", "task", "Ticket type (bug, feature, task)")
	createCmd.Flags().StringVarP(&priority, "priority", "p", "undefined", "Ticket priority (low, medium, high)")
	createCmd.Flags().BoolVarP(&criticalpath, "criticalpath", "c", false, "Mark ticket as critical path")
	createCmd.Flags().StringVarP(&assignedTo, "assigned-to", "a", "", "Assign ticket to user")
	createCmd.Flags().StringVar(&createdBy, "created-by", "", "Ticket creator")
	createCmd.Flags().StringVar(&tags, "tags", "", "Comma-separated list of tags")
	createCmd.Flags().StringVar(&project, "project", "", "Project name (required)")
	if err := createCmd.MarkFlagRequired("title"); err != nil {
		panic(err)
	}
	if err := createCmd.MarkFlagRequired("project"); err != nil {
		panic(err)
	}

}
